/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Params {
  export type TreeDepthsStruct = {
    tallyProcessingStateTreeDepth: BigNumberish;
    voteOptionTreeDepth: BigNumberish;
    stateTreeDepth: BigNumberish;
  };

  export type TreeDepthsStructOutput = [
    tallyProcessingStateTreeDepth: bigint,
    voteOptionTreeDepth: bigint,
    stateTreeDepth: bigint
  ] & {
    tallyProcessingStateTreeDepth: bigint;
    voteOptionTreeDepth: bigint;
    stateTreeDepth: bigint;
  };

  export type ExtContractsStruct = {
    maci: AddressLike;
    verifier: AddressLike;
    verifyingKeysRegistry: AddressLike;
    policy: AddressLike;
    initialVoiceCreditProxy: AddressLike;
  };

  export type ExtContractsStructOutput = [
    maci: string,
    verifier: string,
    verifyingKeysRegistry: string,
    policy: string,
    initialVoiceCreditProxy: string
  ] & {
    maci: string;
    verifier: string;
    verifyingKeysRegistry: string;
    policy: string;
    initialVoiceCreditProxy: string;
  };
}

export declare namespace DomainObjs {
  export type PublicKeyStruct = { x: BigNumberish; y: BigNumberish };

  export type PublicKeyStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };
}

export declare namespace IPollFactory {
  export type DeployPollArgsStruct = {
    startDate: BigNumberish;
    endDate: BigNumberish;
    treeDepths: Params.TreeDepthsStruct;
    messageBatchSize: BigNumberish;
    coordinatorPublicKey: DomainObjs.PublicKeyStruct;
    extContracts: Params.ExtContractsStruct;
    emptyBallotRoot: BigNumberish;
    pollId: BigNumberish;
    relayers: AddressLike[];
    voteOptions: BigNumberish;
  };

  export type DeployPollArgsStructOutput = [
    startDate: bigint,
    endDate: bigint,
    treeDepths: Params.TreeDepthsStructOutput,
    messageBatchSize: bigint,
    coordinatorPublicKey: DomainObjs.PublicKeyStructOutput,
    extContracts: Params.ExtContractsStructOutput,
    emptyBallotRoot: bigint,
    pollId: bigint,
    relayers: string[],
    voteOptions: bigint
  ] & {
    startDate: bigint;
    endDate: bigint;
    treeDepths: Params.TreeDepthsStructOutput;
    messageBatchSize: bigint;
    coordinatorPublicKey: DomainObjs.PublicKeyStructOutput;
    extContracts: Params.ExtContractsStructOutput;
    emptyBallotRoot: bigint;
    pollId: bigint;
    relayers: string[];
    voteOptions: bigint;
  };
}

export interface PollFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "IMPLEMENTATION" | "MESSAGE_DATA_LENGTH" | "deploy"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CloneDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "IMPLEMENTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MESSAGE_DATA_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deploy",
    values: [IPollFactory.DeployPollArgsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "IMPLEMENTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MESSAGE_DATA_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
}

export namespace CloneDeployedEvent {
  export type InputTuple = [clone: AddressLike];
  export type OutputTuple = [clone: string];
  export interface OutputObject {
    clone: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PollFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PollFactory;
  waitForDeployment(): Promise<this>;

  interface: PollFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  IMPLEMENTATION: TypedContractMethod<[], [string], "view">;

  MESSAGE_DATA_LENGTH: TypedContractMethod<[], [bigint], "view">;

  deploy: TypedContractMethod<
    [_args: IPollFactory.DeployPollArgsStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "IMPLEMENTATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MESSAGE_DATA_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deploy"
  ): TypedContractMethod<
    [_args: IPollFactory.DeployPollArgsStruct],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "CloneDeployed"
  ): TypedContractEvent<
    CloneDeployedEvent.InputTuple,
    CloneDeployedEvent.OutputTuple,
    CloneDeployedEvent.OutputObject
  >;

  filters: {
    "CloneDeployed(address)": TypedContractEvent<
      CloneDeployedEvent.InputTuple,
      CloneDeployedEvent.OutputTuple,
      CloneDeployedEvent.OutputObject
    >;
    CloneDeployed: TypedContractEvent<
      CloneDeployedEvent.InputTuple,
      CloneDeployedEvent.OutputTuple,
      CloneDeployedEvent.OutputObject
    >;
  };
}
