/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Pairing {
  export type G1PointStruct = { x: BigNumberish; y: BigNumberish };

  export type G1PointStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };

  export type G2PointStruct = {
    x: [BigNumberish, BigNumberish];
    y: [BigNumberish, BigNumberish];
  };

  export type G2PointStructOutput = [
    x: [bigint, bigint],
    y: [bigint, bigint]
  ] & { x: [bigint, bigint]; y: [bigint, bigint] };
}

export declare namespace SnarkCommon {
  export type VerifyingKeyStruct = {
    alpha1: Pairing.G1PointStruct;
    beta2: Pairing.G2PointStruct;
    gamma2: Pairing.G2PointStruct;
    delta2: Pairing.G2PointStruct;
    ic: Pairing.G1PointStruct[];
  };

  export type VerifyingKeyStructOutput = [
    alpha1: Pairing.G1PointStructOutput,
    beta2: Pairing.G2PointStructOutput,
    gamma2: Pairing.G2PointStructOutput,
    delta2: Pairing.G2PointStructOutput,
    ic: Pairing.G1PointStructOutput[]
  ] & {
    alpha1: Pairing.G1PointStructOutput;
    beta2: Pairing.G2PointStructOutput;
    gamma2: Pairing.G2PointStructOutput;
    delta2: Pairing.G2PointStructOutput;
    ic: Pairing.G1PointStructOutput[];
  };
}

export declare namespace IVerifyingKeysRegistry {
  export type SetVerifyingKeysBatchArgsStruct = {
    stateTreeDepth: BigNumberish;
    pollStateTreeDepth: BigNumberish;
    tallyProcessingStateTreeDepth: BigNumberish;
    voteOptionTreeDepth: BigNumberish;
    messageBatchSize: BigNumberish;
    modes: BigNumberish[];
    pollJoiningVerifyingKey: SnarkCommon.VerifyingKeyStruct;
    pollJoinedVerifyingKey: SnarkCommon.VerifyingKeyStruct;
    processVerifyingKeys: SnarkCommon.VerifyingKeyStruct[];
    tallyVerifyingKeys: SnarkCommon.VerifyingKeyStruct[];
  };

  export type SetVerifyingKeysBatchArgsStructOutput = [
    stateTreeDepth: bigint,
    pollStateTreeDepth: bigint,
    tallyProcessingStateTreeDepth: bigint,
    voteOptionTreeDepth: bigint,
    messageBatchSize: bigint,
    modes: bigint[],
    pollJoiningVerifyingKey: SnarkCommon.VerifyingKeyStructOutput,
    pollJoinedVerifyingKey: SnarkCommon.VerifyingKeyStructOutput,
    processVerifyingKeys: SnarkCommon.VerifyingKeyStructOutput[],
    tallyVerifyingKeys: SnarkCommon.VerifyingKeyStructOutput[]
  ] & {
    stateTreeDepth: bigint;
    pollStateTreeDepth: bigint;
    tallyProcessingStateTreeDepth: bigint;
    voteOptionTreeDepth: bigint;
    messageBatchSize: bigint;
    modes: bigint[];
    pollJoiningVerifyingKey: SnarkCommon.VerifyingKeyStructOutput;
    pollJoinedVerifyingKey: SnarkCommon.VerifyingKeyStructOutput;
    processVerifyingKeys: SnarkCommon.VerifyingKeyStructOutput[];
    tallyVerifyingKeys: SnarkCommon.VerifyingKeyStructOutput[];
  };
}

export interface VerifyingKeysRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MESSAGE_DATA_LENGTH"
      | "generatePollJoinedVerifyingKeySignature"
      | "generatePollJoiningVerifyingKeySignature"
      | "generateProcessVerifyingKeySignature"
      | "generateTallyVerifyingKeySignature"
      | "getPollJoinedVerifyingKey"
      | "getPollJoinedVerifyingKeyBySignature"
      | "getPollJoiningVerifyingKey"
      | "getPollJoiningVerifyingKeyBySignature"
      | "getProcessVerifyingKey"
      | "getProcessVerifyingKeyBySignature"
      | "getTallyVerifyingKey"
      | "getTallyVerifyingKeyBySignature"
      | "hasProcessVerifyingKey"
      | "hasTallyVerifyingKey"
      | "isPollJoinedVerifyingKeySet"
      | "isPollJoiningVerifyingKeySet"
      | "isProcessVerifyingKeySet"
      | "isTallyVerifyingKeySet"
      | "owner"
      | "renounceOwnership"
      | "setPollJoinedVerifyingKey"
      | "setPollJoiningVerifyingKey"
      | "setProcessVerifyingKey"
      | "setTallyVerifyingKey"
      | "setVerifyingKeys"
      | "setVerifyingKeysBatch"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PollJoinedVerifyingKeySet"
      | "PollJoiningVerifyingKeySet"
      | "ProcessVerifyingKeySet"
      | "TallyVerifyingKeySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MESSAGE_DATA_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generatePollJoinedVerifyingKeySignature",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "generatePollJoiningVerifyingKeySignature",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "generateProcessVerifyingKeySignature",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "generateTallyVerifyingKeySignature",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollJoinedVerifyingKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollJoinedVerifyingKeyBySignature",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollJoiningVerifyingKey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollJoiningVerifyingKeyBySignature",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProcessVerifyingKey",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProcessVerifyingKeyBySignature",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTallyVerifyingKey",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTallyVerifyingKeyBySignature",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasProcessVerifyingKey",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasTallyVerifyingKey",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPollJoinedVerifyingKeySet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPollJoiningVerifyingKeySet",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProcessVerifyingKeySet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTallyVerifyingKeySet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPollJoinedVerifyingKey",
    values: [BigNumberish, SnarkCommon.VerifyingKeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setPollJoiningVerifyingKey",
    values: [BigNumberish, SnarkCommon.VerifyingKeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessVerifyingKey",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      SnarkCommon.VerifyingKeyStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setTallyVerifyingKey",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      SnarkCommon.VerifyingKeyStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifyingKeys",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      SnarkCommon.VerifyingKeyStruct,
      SnarkCommon.VerifyingKeyStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifyingKeysBatch",
    values: [IVerifyingKeysRegistry.SetVerifyingKeysBatchArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MESSAGE_DATA_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generatePollJoinedVerifyingKeySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generatePollJoiningVerifyingKeySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateProcessVerifyingKeySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateTallyVerifyingKeySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPollJoinedVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPollJoinedVerifyingKeyBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPollJoiningVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPollJoiningVerifyingKeyBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProcessVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProcessVerifyingKeyBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTallyVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTallyVerifyingKeyBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasProcessVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasTallyVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPollJoinedVerifyingKeySet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPollJoiningVerifyingKeySet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProcessVerifyingKeySet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTallyVerifyingKeySet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPollJoinedVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPollJoiningVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTallyVerifyingKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifyingKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVerifyingKeysBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PollJoinedVerifyingKeySetEvent {
  export type InputTuple = [_signature: BigNumberish];
  export type OutputTuple = [_signature: bigint];
  export interface OutputObject {
    _signature: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PollJoiningVerifyingKeySetEvent {
  export type InputTuple = [_signature: BigNumberish];
  export type OutputTuple = [_signature: bigint];
  export interface OutputObject {
    _signature: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessVerifyingKeySetEvent {
  export type InputTuple = [_signature: BigNumberish, _mode: BigNumberish];
  export type OutputTuple = [_signature: bigint, _mode: bigint];
  export interface OutputObject {
    _signature: bigint;
    _mode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TallyVerifyingKeySetEvent {
  export type InputTuple = [_signature: BigNumberish, _mode: BigNumberish];
  export type OutputTuple = [_signature: bigint, _mode: bigint];
  export interface OutputObject {
    _signature: bigint;
    _mode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerifyingKeysRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VerifyingKeysRegistry;
  waitForDeployment(): Promise<this>;

  interface: VerifyingKeysRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MESSAGE_DATA_LENGTH: TypedContractMethod<[], [bigint], "view">;

  generatePollJoinedVerifyingKeySignature: TypedContractMethod<
    [_stateTreeDepth: BigNumberish],
    [bigint],
    "view"
  >;

  generatePollJoiningVerifyingKeySignature: TypedContractMethod<
    [_stateTreeDepth: BigNumberish],
    [bigint],
    "view"
  >;

  generateProcessVerifyingKeySignature: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish
    ],
    [bigint],
    "view"
  >;

  generateTallyVerifyingKeySignature: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getPollJoinedVerifyingKey: TypedContractMethod<
    [_stateTreeDepth: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  getPollJoinedVerifyingKeyBySignature: TypedContractMethod<
    [_signature: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  getPollJoiningVerifyingKey: TypedContractMethod<
    [_stateTreeDepth: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  getPollJoiningVerifyingKeyBySignature: TypedContractMethod<
    [_signature: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  getProcessVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish
    ],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  getProcessVerifyingKeyBySignature: TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  getTallyVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _mode: BigNumberish
    ],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  getTallyVerifyingKeyBySignature: TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;

  hasProcessVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish
    ],
    [boolean],
    "view"
  >;

  hasTallyVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _mode: BigNumberish
    ],
    [boolean],
    "view"
  >;

  isPollJoinedVerifyingKeySet: TypedContractMethod<
    [_signature: BigNumberish],
    [boolean],
    "view"
  >;

  isPollJoiningVerifyingKeySet: TypedContractMethod<
    [_signature: BigNumberish],
    [boolean],
    "view"
  >;

  isProcessVerifyingKeySet: TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [boolean],
    "view"
  >;

  isTallyVerifyingKeySet: TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPollJoinedVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _pollJoinedVerifyingSignature: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;

  setPollJoiningVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _pollJoiningVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;

  setProcessVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish,
      _processVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;

  setTallyVerifyingKey: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _mode: BigNumberish,
      _tallyVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;

  setVerifyingKeys: TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish,
      _processVerifyingKey: SnarkCommon.VerifyingKeyStruct,
      _tallyVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;

  setVerifyingKeysBatch: TypedContractMethod<
    [_args: IVerifyingKeysRegistry.SetVerifyingKeysBatchArgsStruct],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MESSAGE_DATA_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "generatePollJoinedVerifyingKeySignature"
  ): TypedContractMethod<[_stateTreeDepth: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "generatePollJoiningVerifyingKeySignature"
  ): TypedContractMethod<[_stateTreeDepth: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "generateProcessVerifyingKeySignature"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "generateTallyVerifyingKeySignature"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPollJoinedVerifyingKey"
  ): TypedContractMethod<
    [_stateTreeDepth: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPollJoinedVerifyingKeyBySignature"
  ): TypedContractMethod<
    [_signature: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPollJoiningVerifyingKey"
  ): TypedContractMethod<
    [_stateTreeDepth: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPollJoiningVerifyingKeyBySignature"
  ): TypedContractMethod<
    [_signature: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProcessVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish
    ],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProcessVerifyingKeyBySignature"
  ): TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTallyVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _mode: BigNumberish
    ],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTallyVerifyingKeyBySignature"
  ): TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [SnarkCommon.VerifyingKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasProcessVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasTallyVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _mode: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPollJoinedVerifyingKeySet"
  ): TypedContractMethod<[_signature: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPollJoiningVerifyingKeySet"
  ): TypedContractMethod<[_signature: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProcessVerifyingKeySet"
  ): TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTallyVerifyingKeySet"
  ): TypedContractMethod<
    [_signature: BigNumberish, _mode: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPollJoinedVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _pollJoinedVerifyingSignature: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPollJoiningVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _pollJoiningVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProcessVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish,
      _processVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTallyVerifyingKey"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _mode: BigNumberish,
      _tallyVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerifyingKeys"
  ): TypedContractMethod<
    [
      _stateTreeDepth: BigNumberish,
      _intStateTreeDepth: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _messageBatchSize: BigNumberish,
      _mode: BigNumberish,
      _processVerifyingKey: SnarkCommon.VerifyingKeyStruct,
      _tallyVerifyingKey: SnarkCommon.VerifyingKeyStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerifyingKeysBatch"
  ): TypedContractMethod<
    [_args: IVerifyingKeysRegistry.SetVerifyingKeysBatchArgsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PollJoinedVerifyingKeySet"
  ): TypedContractEvent<
    PollJoinedVerifyingKeySetEvent.InputTuple,
    PollJoinedVerifyingKeySetEvent.OutputTuple,
    PollJoinedVerifyingKeySetEvent.OutputObject
  >;
  getEvent(
    key: "PollJoiningVerifyingKeySet"
  ): TypedContractEvent<
    PollJoiningVerifyingKeySetEvent.InputTuple,
    PollJoiningVerifyingKeySetEvent.OutputTuple,
    PollJoiningVerifyingKeySetEvent.OutputObject
  >;
  getEvent(
    key: "ProcessVerifyingKeySet"
  ): TypedContractEvent<
    ProcessVerifyingKeySetEvent.InputTuple,
    ProcessVerifyingKeySetEvent.OutputTuple,
    ProcessVerifyingKeySetEvent.OutputObject
  >;
  getEvent(
    key: "TallyVerifyingKeySet"
  ): TypedContractEvent<
    TallyVerifyingKeySetEvent.InputTuple,
    TallyVerifyingKeySetEvent.OutputTuple,
    TallyVerifyingKeySetEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PollJoinedVerifyingKeySet(uint256)": TypedContractEvent<
      PollJoinedVerifyingKeySetEvent.InputTuple,
      PollJoinedVerifyingKeySetEvent.OutputTuple,
      PollJoinedVerifyingKeySetEvent.OutputObject
    >;
    PollJoinedVerifyingKeySet: TypedContractEvent<
      PollJoinedVerifyingKeySetEvent.InputTuple,
      PollJoinedVerifyingKeySetEvent.OutputTuple,
      PollJoinedVerifyingKeySetEvent.OutputObject
    >;

    "PollJoiningVerifyingKeySet(uint256)": TypedContractEvent<
      PollJoiningVerifyingKeySetEvent.InputTuple,
      PollJoiningVerifyingKeySetEvent.OutputTuple,
      PollJoiningVerifyingKeySetEvent.OutputObject
    >;
    PollJoiningVerifyingKeySet: TypedContractEvent<
      PollJoiningVerifyingKeySetEvent.InputTuple,
      PollJoiningVerifyingKeySetEvent.OutputTuple,
      PollJoiningVerifyingKeySetEvent.OutputObject
    >;

    "ProcessVerifyingKeySet(uint256,uint8)": TypedContractEvent<
      ProcessVerifyingKeySetEvent.InputTuple,
      ProcessVerifyingKeySetEvent.OutputTuple,
      ProcessVerifyingKeySetEvent.OutputObject
    >;
    ProcessVerifyingKeySet: TypedContractEvent<
      ProcessVerifyingKeySetEvent.InputTuple,
      ProcessVerifyingKeySetEvent.OutputTuple,
      ProcessVerifyingKeySetEvent.OutputObject
    >;

    "TallyVerifyingKeySet(uint256,uint8)": TypedContractEvent<
      TallyVerifyingKeySetEvent.InputTuple,
      TallyVerifyingKeySetEvent.OutputTuple,
      TallyVerifyingKeySetEvent.OutputObject
    >;
    TallyVerifyingKeySet: TypedContractEvent<
      TallyVerifyingKeySetEvent.InputTuple,
      TallyVerifyingKeySetEvent.OutputTuple,
      TallyVerifyingKeySetEvent.OutputObject
    >;
  };
}
