/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20VotesChecker__factory } from "./ERC20VotesChecker__factory";
export { ERC20VotesCheckerFactory__factory } from "./ERC20VotesCheckerFactory__factory";
export { ERC20VotesPolicy__factory } from "./ERC20VotesPolicy__factory";
export { ERC20VotesPolicyFactory__factory } from "./ERC20VotesPolicyFactory__factory";
