/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  FreeForAllChecker,
  FreeForAllCheckerInterface,
} from "../../../../../../@excubiae/contracts/contracts/extensions/freeForAll/FreeForAllChecker";

const _abi = [
  {
    inputs: [],
    name: "AlreadyInitialized",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "subject",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "evidence",
        type: "bytes",
      },
    ],
    name: "check",
    outputs: [
      {
        internalType: "bool",
        name: "checked",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAppendedBytes",
    outputs: [
      {
        internalType: "bytes",
        name: "appendedBytes",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "initialized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061024d8061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c8063158ef93e146100515780638129fc1c14610073578063b41a4b191461007d578063e2b2408514610092575b600080fd5b60005461005e9060ff1681565b60405190151581526020015b60405180910390f35b61007b6100a9565b005b6100856100b3565b60405161006a9190610136565b61005e6100a0366004610184565b50600192915050565b6100b16100c2565b565b60606100bd6100ca565b905090565b6100b16100d5565b60606100bd30610107565b60005460ff16156100f85760405162dc149f60e41b815260040160405180910390fd5b6000805460ff19166001179055565b60405164ffffffffff602c19833b0116808252602090810190602d908301843c60408101815101604052919050565b602081526000825180602084015260005b818110156101645760208186018101516040868401015201610147565b506000604082850101526040601f19601f83011684010191505092915050565b60008060006040848603121561019957600080fd5b83356001600160a01b03811681146101b057600080fd5b9250602084013567ffffffffffffffff8111156101cc57600080fd5b8401601f810186136101dd57600080fd5b803567ffffffffffffffff8111156101f457600080fd5b86602082840101111561020657600080fd5b93966020919091019550929350505056fea2646970667358221220c30430394fbaf0d4d4c912a3b6ce777e09203b6b60d5fd436e50b7e7cf0dbeb264736f6c634300081c0033";

type FreeForAllCheckerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: FreeForAllCheckerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class FreeForAllChecker__factory extends ContractFactory {
  constructor(...args: FreeForAllCheckerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      FreeForAllChecker & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): FreeForAllChecker__factory {
    return super.connect(runner) as FreeForAllChecker__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FreeForAllCheckerInterface {
    return new Interface(_abi) as FreeForAllCheckerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): FreeForAllChecker {
    return new Contract(address, _abi, runner) as unknown as FreeForAllChecker;
  }
}
