/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../../common";
import type {
  MockGitcoinPassportDecoder,
  MockGitcoinPassportDecoderInterface,
} from "../../../../../../../@excubiae/contracts/contracts/test/extensions/mocks/MockGitcoinPassportDecoder";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newScore",
        type: "uint256",
      },
    ],
    name: "changeScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "score",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060fb8061001e6000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c806329044119146041578063d47875d0146053578063efedc669146077575b600080fd5b6051604c366004607f565b600055565b005b6065605e3660046097565b5060005490565b60405190815260200160405180910390f35b606560005481565b600060208284031215609057600080fd5b5035919050565b60006020828403121560a857600080fd5b81356001600160a01b038116811460be57600080fd5b939250505056fea2646970667358221220359b3660d08185045889af17c1244d8c3adec8f464e0c0de53a5fae113b6eb8264736f6c634300081c0033";

type MockGitcoinPassportDecoderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockGitcoinPassportDecoderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockGitcoinPassportDecoder__factory extends ContractFactory {
  constructor(...args: MockGitcoinPassportDecoderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockGitcoinPassportDecoder & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockGitcoinPassportDecoder__factory {
    return super.connect(runner) as MockGitcoinPassportDecoder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockGitcoinPassportDecoderInterface {
    return new Interface(_abi) as MockGitcoinPassportDecoderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockGitcoinPassportDecoder {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockGitcoinPassportDecoder;
  }
}
