packages:
  - apps/*
  - packages/*
catalog:
  "@eslint/eslintrc": ^3
  "@eslint/js": ^9.30.0
  "@next/eslint-plugin-next": ^15.3.0
  "@tailwindcss/postcss": ^4
  eslint-config-next: 15.3.5
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.3.0
  next: 15.3.0
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4
  turbo: ^2.5.4
  typescript-eslint: ^8.35.0
