/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Params {
  export type TreeDepthsStruct = {
    tallyProcessingStateTreeDepth: BigNumberish;
    voteOptionTreeDepth: BigNumberish;
    stateTreeDepth: BigNumberish;
  };

  export type TreeDepthsStructOutput = [
    tallyProcessingStateTreeDepth: bigint,
    voteOptionTreeDepth: bigint,
    stateTreeDepth: bigint
  ] & {
    tallyProcessingStateTreeDepth: bigint;
    voteOptionTreeDepth: bigint;
    stateTreeDepth: bigint;
  };
}

export declare namespace DomainObjs {
  export type PublicKeyStruct = { x: BigNumberish; y: BigNumberish };

  export type PublicKeyStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };
}

export declare namespace IMACI {
  export type DeployPollArgsStruct = {
    startDate: BigNumberish;
    endDate: BigNumberish;
    treeDepths: Params.TreeDepthsStruct;
    messageBatchSize: BigNumberish;
    coordinatorPublicKey: DomainObjs.PublicKeyStruct;
    verifier: AddressLike;
    verifyingKeysRegistry: AddressLike;
    mode: BigNumberish;
    policy: AddressLike;
    initialVoiceCreditProxy: AddressLike;
    relayers: AddressLike[];
    voteOptions: BigNumberish;
  };

  export type DeployPollArgsStructOutput = [
    startDate: bigint,
    endDate: bigint,
    treeDepths: Params.TreeDepthsStructOutput,
    messageBatchSize: bigint,
    coordinatorPublicKey: DomainObjs.PublicKeyStructOutput,
    verifier: string,
    verifyingKeysRegistry: string,
    mode: bigint,
    policy: string,
    initialVoiceCreditProxy: string,
    relayers: string[],
    voteOptions: bigint
  ] & {
    startDate: bigint;
    endDate: bigint;
    treeDepths: Params.TreeDepthsStructOutput;
    messageBatchSize: bigint;
    coordinatorPublicKey: DomainObjs.PublicKeyStructOutput;
    verifier: string;
    verifyingKeysRegistry: string;
    mode: bigint;
    policy: string;
    initialVoiceCreditProxy: string;
    relayers: string[];
    voteOptions: bigint;
  };

  export type PollContractsStruct = {
    poll: AddressLike;
    messageProcessor: AddressLike;
    tally: AddressLike;
  };

  export type PollContractsStructOutput = [
    poll: string,
    messageProcessor: string,
    tally: string
  ] & { poll: string; messageProcessor: string; tally: string };
}

export interface IMACIInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployPoll"
      | "getStateIndex"
      | "getStateRootOnIndexedSignUp"
      | "getStateTreeRoot"
      | "nextPollId"
      | "signUp"
      | "stateTreeDepth"
      | "totalSignups"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployPoll",
    values: [IMACI.DeployPollArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateRootOnIndexedSignUp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateTreeRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextPollId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signUp",
    values: [DomainObjs.PublicKeyStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stateTreeDepth",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSignups",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "deployPoll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStateIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateRootOnIndexedSignUp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateTreeRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextPollId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stateTreeDepth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSignups",
    data: BytesLike
  ): Result;
}

export interface IMACI extends BaseContract {
  connect(runner?: ContractRunner | null): IMACI;
  waitForDeployment(): Promise<this>;

  interface: IMACIInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deployPoll: TypedContractMethod<
    [_pollArgs: IMACI.DeployPollArgsStruct],
    [IMACI.PollContractsStructOutput],
    "nonpayable"
  >;

  getStateIndex: TypedContractMethod<
    [_publicKeyHash: BigNumberish],
    [bigint],
    "view"
  >;

  getStateRootOnIndexedSignUp: TypedContractMethod<
    [_index: BigNumberish],
    [bigint],
    "view"
  >;

  getStateTreeRoot: TypedContractMethod<[], [bigint], "view">;

  nextPollId: TypedContractMethod<[], [bigint], "view">;

  signUp: TypedContractMethod<
    [_publicKey: DomainObjs.PublicKeyStruct, _signUpPolicyData: BytesLike],
    [void],
    "nonpayable"
  >;

  stateTreeDepth: TypedContractMethod<[], [bigint], "view">;

  totalSignups: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deployPoll"
  ): TypedContractMethod<
    [_pollArgs: IMACI.DeployPollArgsStruct],
    [IMACI.PollContractsStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getStateIndex"
  ): TypedContractMethod<[_publicKeyHash: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStateRootOnIndexedSignUp"
  ): TypedContractMethod<[_index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStateTreeRoot"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextPollId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "signUp"
  ): TypedContractMethod<
    [_publicKey: DomainObjs.PublicKeyStruct, _signUpPolicyData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stateTreeDepth"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSignups"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
