/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Params {
  export type TreeDepthsStruct = {
    tallyProcessingStateTreeDepth: BigNumberish;
    voteOptionTreeDepth: BigNumberish;
    stateTreeDepth: BigNumberish;
  };

  export type TreeDepthsStructOutput = [
    tallyProcessingStateTreeDepth: bigint,
    voteOptionTreeDepth: bigint,
    stateTreeDepth: bigint
  ] & {
    tallyProcessingStateTreeDepth: bigint;
    voteOptionTreeDepth: bigint;
    stateTreeDepth: bigint;
  };

  export type ExtContractsStruct = {
    maci: AddressLike;
    verifier: AddressLike;
    verifyingKeysRegistry: AddressLike;
    policy: AddressLike;
    initialVoiceCreditProxy: AddressLike;
  };

  export type ExtContractsStructOutput = [
    maci: string,
    verifier: string,
    verifyingKeysRegistry: string,
    policy: string,
    initialVoiceCreditProxy: string
  ] & {
    maci: string;
    verifier: string;
    verifyingKeysRegistry: string;
    policy: string;
    initialVoiceCreditProxy: string;
  };
}

export declare namespace DomainObjs {
  export type PublicKeyStruct = { x: BigNumberish; y: BigNumberish };

  export type PublicKeyStructOutput = [x: bigint, y: bigint] & {
    x: bigint;
    y: bigint;
  };
}

export declare namespace IPollFactory {
  export type DeployPollArgsStruct = {
    startDate: BigNumberish;
    endDate: BigNumberish;
    treeDepths: Params.TreeDepthsStruct;
    messageBatchSize: BigNumberish;
    coordinatorPublicKey: DomainObjs.PublicKeyStruct;
    extContracts: Params.ExtContractsStruct;
    emptyBallotRoot: BigNumberish;
    pollId: BigNumberish;
    relayers: AddressLike[];
    voteOptions: BigNumberish;
  };

  export type DeployPollArgsStructOutput = [
    startDate: bigint,
    endDate: bigint,
    treeDepths: Params.TreeDepthsStructOutput,
    messageBatchSize: bigint,
    coordinatorPublicKey: DomainObjs.PublicKeyStructOutput,
    extContracts: Params.ExtContractsStructOutput,
    emptyBallotRoot: bigint,
    pollId: bigint,
    relayers: string[],
    voteOptions: bigint
  ] & {
    startDate: bigint;
    endDate: bigint;
    treeDepths: Params.TreeDepthsStructOutput;
    messageBatchSize: bigint;
    coordinatorPublicKey: DomainObjs.PublicKeyStructOutput;
    extContracts: Params.ExtContractsStructOutput;
    emptyBallotRoot: bigint;
    pollId: bigint;
    relayers: string[];
    voteOptions: bigint;
  };
}

export interface IPollFactoryInterface extends Interface {
  getFunction(nameOrSignature: "deploy"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deploy",
    values: [IPollFactory.DeployPollArgsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
}

export interface IPollFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IPollFactory;
  waitForDeployment(): Promise<this>;

  interface: IPollFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deploy: TypedContractMethod<
    [_args: IPollFactory.DeployPollArgsStruct],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deploy"
  ): TypedContractMethod<
    [_args: IPollFactory.DeployPollArgsStruct],
    [string],
    "nonpayable"
  >;

  filters: {};
}
