import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Web3Provider } from "../providers/Web3Provider";
import { MockProvider } from "./mock-provider";
import { RootNav } from "./RootNav";
import { FeedbackProvider } from "@/contexts/FeedbackContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { WalletConnectOverlay } from "@/components/WalletConnectOverlay";
import { cookies } from "next/headers";

// Force dynamic rendering for routes that use cookies
export const dynamic = "force-dynamic";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "SaSvoth App",
  description: "Generated by create next app",
};

async function getCurrentUser() {
  try {
    const cookieStore = await cookies();
    const cookieHeader = cookieStore
      .getAll()
      .map(({ name, value }) => `${name}=${value}`)
      .join("; ");

    const apiBase =
      process.env.API_URL ||
      (process.env.NEXT_PUBLIC_API_URL?.startsWith("http")
        ? process.env.NEXT_PUBLIC_API_URL
        : "http://localhost:8000");
    const userEndpoint = new URL("/api/v1/users/me", apiBase).toString();

    // Helper to refresh token
    const refreshToken = async () => {
      try {
        const refreshEndpoint = new URL(
          "/api/v1/auth/refresh",
          apiBase,
        ).toString();
        const res = await fetch(refreshEndpoint, {
          method: "POST",
          headers: {
            Accept: "application/json",
            "Content-Type": "application/json",
            ...(cookieHeader ? { cookie: cookieHeader } : {}),
          },
          cache: "no-store",
        });
        return res.ok;
      } catch (err) {
        return false;
      }
    };

    let res = await fetch(userEndpoint, {
      method: "GET",
      headers: {
        Accept: "application/json",
        ...(cookieHeader ? { cookie: cookieHeader } : {}),
      },
      cache: "no-store",
    });

    if (res.status === 401) {
      const refreshed = await refreshToken();
      if (refreshed) {
        res = await fetch(userEndpoint, {
          method: "GET",
          headers: {
            Accept: "application/json",
            ...(cookieHeader ? { cookie: cookieHeader } : {}),
          },
          cache: "no-store",
        });
      } else {
        return null;
      }
    }

    if (!res.ok) return null;
    const data = await res.json();
    return data?.data ?? data; // Handle likely wrapper { data: user }
  } catch (err) {
    console.error("Layout user fetch failed", err);
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Web3Provider>
          <AuthProvider initialUser={user}>
            <MockProvider />
            <RootNav />
            <WalletConnectOverlay />
            <FeedbackProvider>{children}</FeedbackProvider>
          </AuthProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
