/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBaseChecker } from "./IBaseChecker";
export type { IBasePolicy } from "./IBasePolicy";
export type { IClone } from "./IClone";
export type { IFactory } from "./IFactory";
export type { IPolicy } from "./IPolicy";
