/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  BaseChecker,
  BaseCheckerInterface,
} from "../../../../../@excubiae/contracts/contracts/checker/BaseChecker";

const _abi = [
  {
    inputs: [],
    name: "AlreadyInitialized",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "subject",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "evidence",
        type: "bytes",
      },
    ],
    name: "check",
    outputs: [
      {
        internalType: "bool",
        name: "checked",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAppendedBytes",
    outputs: [
      {
        internalType: "bytes",
        name: "appendedBytes",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "initialized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class BaseChecker__factory {
  static readonly abi = _abi;
  static createInterface(): BaseCheckerInterface {
    return new Interface(_abi) as BaseCheckerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): BaseChecker {
    return new Contract(address, _abi, runner) as unknown as BaseChecker;
  }
}
