/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IBasePolicyInterface extends Interface {
  getFunction(
    nameOrSignature: "enforce" | "setTarget" | "trait"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Enforced" | "TargetSet"): EventFragment;

  encodeFunctionData(
    functionFragment: "enforce",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "trait", values?: undefined): string;

  decodeFunctionResult(functionFragment: "enforce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trait", data: BytesLike): Result;
}

export namespace EnforcedEvent {
  export type InputTuple = [
    subject: AddressLike,
    guarded: AddressLike,
    evidence: BytesLike
  ];
  export type OutputTuple = [
    subject: string,
    guarded: string,
    evidence: string
  ];
  export interface OutputObject {
    subject: string;
    guarded: string;
    evidence: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetSetEvent {
  export type InputTuple = [guarded: AddressLike];
  export type OutputTuple = [guarded: string];
  export interface OutputObject {
    guarded: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBasePolicy extends BaseContract {
  connect(runner?: ContractRunner | null): IBasePolicy;
  waitForDeployment(): Promise<this>;

  interface: IBasePolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  enforce: TypedContractMethod<
    [subject: AddressLike, evidence: BytesLike],
    [void],
    "nonpayable"
  >;

  setTarget: TypedContractMethod<[_guarded: AddressLike], [void], "nonpayable">;

  trait: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "enforce"
  ): TypedContractMethod<
    [subject: AddressLike, evidence: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTarget"
  ): TypedContractMethod<[_guarded: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trait"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Enforced"
  ): TypedContractEvent<
    EnforcedEvent.InputTuple,
    EnforcedEvent.OutputTuple,
    EnforcedEvent.OutputObject
  >;
  getEvent(
    key: "TargetSet"
  ): TypedContractEvent<
    TargetSetEvent.InputTuple,
    TargetSetEvent.OutputTuple,
    TargetSetEvent.OutputObject
  >;

  filters: {
    "Enforced(address,address,bytes)": TypedContractEvent<
      EnforcedEvent.InputTuple,
      EnforcedEvent.OutputTuple,
      EnforcedEvent.OutputObject
    >;
    Enforced: TypedContractEvent<
      EnforcedEvent.InputTuple,
      EnforcedEvent.OutputTuple,
      EnforcedEvent.OutputObject
    >;

    "TargetSet(address)": TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
    TargetSet: TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
  };
}
