/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IPolicyInterface extends Interface {
  getFunction(nameOrSignature: "setTarget" | "trait"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TargetSet"): EventFragment;

  encodeFunctionData(
    functionFragment: "setTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "trait", values?: undefined): string;

  decodeFunctionResult(functionFragment: "setTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trait", data: BytesLike): Result;
}

export namespace TargetSetEvent {
  export type InputTuple = [guarded: AddressLike];
  export type OutputTuple = [guarded: string];
  export interface OutputObject {
    guarded: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPolicy extends BaseContract {
  connect(runner?: ContractRunner | null): IPolicy;
  waitForDeployment(): Promise<this>;

  interface: IPolicyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setTarget: TypedContractMethod<[_guarded: AddressLike], [void], "nonpayable">;

  trait: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setTarget"
  ): TypedContractMethod<[_guarded: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trait"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "TargetSet"
  ): TypedContractEvent<
    TargetSetEvent.InputTuple,
    TargetSetEvent.OutputTuple,
    TargetSetEvent.OutputObject
  >;

  filters: {
    "TargetSet(address)": TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
    TargetSet: TypedContractEvent<
      TargetSetEvent.InputTuple,
      TargetSetEvent.OutputTuple,
      TargetSetEvent.OutputObject
    >;
  };
}
