/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPollFactory,
  IPollFactoryInterface,
} from "../../../contracts/interfaces/IPollFactory";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "startDate",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endDate",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint8",
                name: "tallyProcessingStateTreeDepth",
                type: "uint8",
              },
              {
                internalType: "uint8",
                name: "voteOptionTreeDepth",
                type: "uint8",
              },
              {
                internalType: "uint8",
                name: "stateTreeDepth",
                type: "uint8",
              },
            ],
            internalType: "struct Params.TreeDepths",
            name: "treeDepths",
            type: "tuple",
          },
          {
            internalType: "uint8",
            name: "messageBatchSize",
            type: "uint8",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "x",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "y",
                type: "uint256",
              },
            ],
            internalType: "struct DomainObjs.PublicKey",
            name: "coordinatorPublicKey",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "contract IMACI",
                name: "maci",
                type: "address",
              },
              {
                internalType: "contract IVerifier",
                name: "verifier",
                type: "address",
              },
              {
                internalType: "contract IVerifyingKeysRegistry",
                name: "verifyingKeysRegistry",
                type: "address",
              },
              {
                internalType: "contract IBasePolicy",
                name: "policy",
                type: "address",
              },
              {
                internalType: "contract IInitialVoiceCreditProxy",
                name: "initialVoiceCreditProxy",
                type: "address",
              },
            ],
            internalType: "struct Params.ExtContracts",
            name: "extContracts",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "emptyBallotRoot",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pollId",
            type: "uint256",
          },
          {
            internalType: "address[]",
            name: "relayers",
            type: "address[]",
          },
          {
            internalType: "uint256",
            name: "voteOptions",
            type: "uint256",
          },
        ],
        internalType: "struct IPollFactory.DeployPollArgs",
        name: "_args",
        type: "tuple",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPollFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPollFactoryInterface {
    return new Interface(_abi) as IPollFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPollFactory {
    return new Contract(address, _abi, runner) as unknown as IPollFactory;
  }
}
