/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface EASCheckerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attester"
      | "check"
      | "eas"
      | "getAppendedBytes"
      | "initialize"
      | "initialized"
      | "schema"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "attester", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "check",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "eas", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAppendedBytes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "schema", values?: undefined): string;

  decodeFunctionResult(functionFragment: "attester", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAppendedBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schema", data: BytesLike): Result;
}

export interface EASChecker extends BaseContract {
  connect(runner?: ContractRunner | null): EASChecker;
  waitForDeployment(): Promise<this>;

  interface: EASCheckerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attester: TypedContractMethod<[], [string], "view">;

  check: TypedContractMethod<
    [subject: AddressLike, evidence: BytesLike],
    [boolean],
    "view"
  >;

  eas: TypedContractMethod<[], [string], "view">;

  getAppendedBytes: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  initialized: TypedContractMethod<[], [boolean], "view">;

  schema: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attester"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "check"
  ): TypedContractMethod<
    [subject: AddressLike, evidence: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "eas"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAppendedBytes"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "schema"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
