/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBaseChecker,
  IBaseCheckerInterface,
} from "../../../../../@excubiae/contracts/contracts/interfaces/IBaseChecker";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "subject",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "evidence",
        type: "bytes",
      },
    ],
    name: "check",
    outputs: [
      {
        internalType: "bool",
        name: "checked",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBaseChecker__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseCheckerInterface {
    return new Interface(_abi) as IBaseCheckerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBaseChecker {
    return new Contract(address, _abi, runner) as unknown as IBaseChecker;
  }
}
