/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBasePolicy,
  IBasePolicyInterface,
} from "../../../../../@excubiae/contracts/contracts/interfaces/IBasePolicy";

const _abi = [
  {
    inputs: [],
    name: "AlreadyEnforced",
    type: "error",
  },
  {
    inputs: [],
    name: "TargetAlreadySet",
    type: "error",
  },
  {
    inputs: [],
    name: "TargetNotSet",
    type: "error",
  },
  {
    inputs: [],
    name: "TargetOnly",
    type: "error",
  },
  {
    inputs: [],
    name: "UnsuccessfulCheck",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "subject",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "guarded",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "evidence",
        type: "bytes",
      },
    ],
    name: "Enforced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "guarded",
        type: "address",
      },
    ],
    name: "TargetSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "subject",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "evidence",
        type: "bytes",
      },
    ],
    name: "enforce",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_guarded",
        type: "address",
      },
    ],
    name: "setTarget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "trait",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IBasePolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IBasePolicyInterface {
    return new Interface(_abi) as IBasePolicyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBasePolicy {
    return new Contract(address, _abi, runner) as unknown as IBasePolicy;
  }
}
