/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBaseChecker__factory } from "./IBaseChecker__factory";
export { IBasePolicy__factory } from "./IBasePolicy__factory";
export { IClone__factory } from "./IClone__factory";
export { IFactory__factory } from "./IFactory__factory";
export { IPolicy__factory } from "./IPolicy__factory";
